//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
extern "C" __declspec(dllimport) int __stdcall IsDebuggerPresent();
#endif

#include "RemotingPage.xaml.h"

void ::RemotingHostSample::RemotingPage::InitializeComponent()
{
    if (_contentLoaded)
    {
        return;
    }
    _contentLoaded = true;
    ::Windows::Foundation::Uri^ resourceLocator = ref new ::Windows::Foundation::Uri(L"ms-appx:///RemotingPage.xaml");
    ::Windows::UI::Xaml::Application::LoadComponent(this, resourceLocator, ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);
}

void ::RemotingHostSample::RemotingPage::Connect(int __connectionId, ::Platform::Object^ __target)
{
    switch (__connectionId)
    {
        case 1:
            {
                this->swapChainPanel = safe_cast<::Windows::UI::Xaml::Controls::SwapChainPanel^>(__target);
            }
            break;
        case 2:
            {
                this->ipAddress = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(this->ipAddress))->TextChanged += ref new ::Windows::UI::Xaml::Controls::TextChangedEventHandler(this, (void (::RemotingHostSample::RemotingPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Controls::TextChangedEventArgs^))&RemotingPage::ipAddress_TextChanged);
                (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(this->ipAddress))->KeyDown += ref new ::Windows::UI::Xaml::Input::KeyEventHandler(this, (void (::RemotingHostSample::RemotingPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::KeyRoutedEventArgs^))&RemotingPage::Key_Down);
            }
            break;
        case 3:
            {
                this->Start = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->Start))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::RemotingHostSample::RemotingPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&RemotingPage::Start_Click);
            }
            break;
        case 4:
            {
                this->Stop = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->Stop))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::RemotingHostSample::RemotingPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&RemotingPage::Stop_Click);
            }
            break;
        case 5:
            {
                this->TogglePreview = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->TogglePreview))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::RemotingHostSample::RemotingPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&RemotingPage::Toggle_Preview);
            }
            break;
        case 6:
            {
                this->Console = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
            }
            break;
    }
    _contentLoaded = true;
}

::Windows::UI::Xaml::Markup::IComponentConnector^ ::RemotingHostSample::RemotingPage::GetBindingConnector(int __connectionId, ::Platform::Object^ __target)
{
    __connectionId;         // unreferenced
    __target;               // unreferenced
    return nullptr;
}


